### PR TITLE
localization fix

### PR DESCRIPTION
**Pull request by ssuchanowski**

### CODE REVIEW

**Comment by ssuchanowski** [comment]
I've changed one letter in localized string, travis is broken a little bit:

⌦ /Users/travis/build/tomguthrie/TFGRelativeDateFormatter/Tests/TFGRelativeDateFormatterTests.m:11:9: 'TFGRelativeDateFormatter/TFGRelativeDateFormatter.h' file not found

Could you merge this?

**Comment by tomguthrie** [comment]
What's the reasoning for the change? If you want lowercase "yesterday" it's probably easier to just copy the files into your project and change it there. This change will break things for people expecting the old behaviour.

**Comment by ssuchanowski** [comment]
But why it's breaking? "Yesterday" is wrong, in your localized.strings you have it without capital letter. So reason is that this value is not localized.

**Comment by tomguthrie** [comment]
Are you sure thats not from somewhere else? I haven't added a localized.strings file to the project, only localisation stuff I've done is make sure en_GB and en_US do the right thing.

**Comment by ssuchanowski** [comment]
eh.. rigth, I have those from different project, closing.

BTW. you can copy values from FormatterKit

**Pull request closed without merging**
